version: '3.8'


services:

  rig-mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: RealIsGamer
      MONGO_INITDB_ROOT_PASSWORD: AmstradCPC@1986
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017