export * from './game';
export * from './generic';
export * from './add-basic.dto';
export * from './add-massive.dto';
export * from './add-publisher.dto';
export * from './add-saga.dto';
export * from './add-tag.dto';
export * from './comprobe-basic.dto';
export * from './search-by-name.dto';
export * from './search-by-titulo.dto';
export * from './update-saga.dto';
export * from './delete.dto';
export * from './genre/get-genre.dto';
export * from './platform';
export * from './genre';
export * from './combine'